[package]
name = "aoc_2022_day_21"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../libs/aoc" }
parse-display = "0.10.0"
xxcalc = "0.2.1"
