[package]
name = "aoc_2022_day_09"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../libs/aoc" }
defaultmap = "0.6.0"
derive_more = "0.99.18"
