[package]
name = "aoc_2022_day_13"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../libs/aoc" }
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
