[package]
name = "aoc_2022_day_07"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../libs/aoc" }
indextree = "4.7.0"
