[package]
name = "aoc_2022_day_05"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../../libs/aoc" }
lazy_static = "1.4.0"
regex = "1.10.4"
